### ISSUE TITLE
TODO: improve activity button styling

### ISSUE THREAD

**Issue by MiguelHigueraDev** [MiguelHigueraDev/discord-card-react#1]
Improve the activity button style to better match Discord's styling.

- Add a new `accentColor` prop to `SpotifySection`
- Pass the prop from `BaseDiscordCard` to it
- Use that color as the background color for the anchor element
- Add Spotify logo to the left of the text (Play on Spotify)

Current style
![image](https://github.com/MiguelHigueraDev/discord-card-react/assets/133175356/1de0a567-8af1-4b3b-9ed6-ab06977599c5)

Desired style
![image](https://github.com/MiguelHigueraDev/discord-card-react/assets/133175356/d4cfd3aa-827c-4c1f-a778-6e8249db8313)

**Comment by TomasMatarazzo** [comment]
can i work on this? thx

**Comment by MiguelHigueraDev** [comment]
> can i work on this? thx

Sure, thanks for taking the time to contribute!

**Comment by TomasMatarazzo** [comment]
:) In which file is the button?

**Comment by MiguelHigueraDev** [comment]
It's the button in src/components/SpotifySection.tsx

I'm not at my computer to give you more pointers (like an example) but what I want to do is to use the accent color from the DiscordCard by passing it as a prop and also to add the Spotify logo to the left side of the button text

**Comment by TomasMatarazzo** [comment]
sounds good! thank you

**Comment by MiguelHigueraDev** [comment]
> sounds good! thank you

Feel free to ask if you have any questions

**Comment by TomasMatarazzo** [comment]
Sure, when i start i ll let you know, to show the component i only have to use showSpotify = {true } and priority = 'spotify'?

**Comment by MiguelHigueraDev** [comment]
It's not necessary, I updated the "demo" page to show both Spotify and Game components by default statically, so you don't depend on my current discord status for seeing them.

I'd recommend you to fork the repository and clone it in your local machine so you can start the dev server by using `npm run dev` and watch the changes to the card live. You'll need to fork it to make a pull request anyway

**Comment by MiguelHigueraDev** [comment]
Fixed in #14
