### ISSUE TITLE
styles don't work

### ISSUE THREAD

**Issue by zelear** [MiguelHigueraDev/discord-card-react#25]
For some reason the card styles are not working for me
![Screenshot_2024-05-06-13-58-29-357_com android chrome-edit](https://github.com/MiguelHigueraDev/discord-card-react/assets/140787513/18787232-3e53-4ded-ba9e-6ab073e9b45f)

**Comment by MiguelHigueraDev** [comment]
Did you import the styles by adding this line after the card import?

`import "discord-card-react/styles";`

**Comment by MiguelHigueraDev** [comment]
> > Did you import the styles by adding this line after the card import?
> > `import "discord-card-react/styles";`
> > The card looks like that if you don't import the styles. If it still looks like that after importing them I'll be glad to help.
> 
> Now everything works, but there is a small problem. Could you add a standard profile color if no colors are specified, and also when there is no avatar or banner. In discord you can set the color for the banner. ![Screenshot_2024-05-06-22-15-12-320_com android chrome](https://private-user-images.githubusercontent.com/140787513/328261231-ee875989-851d-41aa-ad76-9e341436be1b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMTczMDQsIm5iZiI6MTcxNTAxNzAwNCwicGF0aCI6Ii8xNDA3ODc1MTMvMzI4MjYxMjMxLWVlODc1OTg5LTg1MWQtNDFhYS1hZDc2LTllMzQxNDM2YmUxYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQxNzM2NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MjNhMjc4OTg3NmQzNzdkZGE5NmM3YTUyODU3ODAxNGZkNzc4NzRmYTI1MzY4ZjQwMDY4ZWNjMjQxMTkzYWY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yZ78SlCOqVJ0VsGrfhiM-eie0uniFXt4m9mpgH3Kw7U)
> 
> and one more question, how to make the card bigger?

Sure. I'll work on adding a default color and also allow for a card with no banner.

About the card size, it's not something that can be changed currently, it has a fixed size like a regular Discord card. I don't think it's something that can be improved on.

**Comment by MiguelHigueraDev** [comment]
I'm gonna move this to another issue and close this one.

**Comment by MiguelHigueraDev** [comment]
I'm gonna move the suggestions to another issue and close this one.
