### ISSUE TITLE
Support multiple activities 

### ISSUE THREAD

**Issue by BossDaily** [MiguelHigueraDev/discord-card-react#28]
I really like this project and one addition I would like to suggest would be adding the ability to see multiple activities in the card, similar to how discord does it.

![image](https://github.com/user-attachments/assets/4a4629d1-0fdd-4e45-8a26-003cbf1dbdc9)

This is also supported in the Lanyard API.

**Comment by MiguelHigueraDev** [comment]
I like the suggestion. Do you think it would be a great idea to add a prop like `maxActivities` to control the maximum number of activities displayed at the same time (default 1)?
